aliyun-oss.endpoint=oss-cn-nanjing.aliyuncs.com
aliyun-oss.bucket=mxy-u
aliyun-oss.dir=images/
aliyun-oss.host=https://mxy-u.oss-cn-nanjing.aliyuncs.com
aliyun-oss.ak=LTAI5tQnFUmsUb2gMFdE7W2d
aliyun-oss.secret=McFDTO4w3onWHaSBjKSnFr05IfQShq