spring:
  data:
    redis:
      port: 6379  # Redis 服务器端口
      host: 127.0.0.1  # Redis 服务器地址
      database: 0 # Redis 数据库的索引，默认为0
      password:   # Redis 服务器密码，默认为空
      lettuce:
        pool:
          min-idle: 10 # 连接池中的最小空闲数，默认为 0
          max-idle: 20 # 连接池中的最大空闲数，默认为 8
          max-active: 100 # 连接池的最大连接数，默认为 8