spring:

  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always

  mail:
    host: smtp.qq.com
    username: 1286280961@qq.com
    password: ypnjcepefhbpigjh
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:6033/spring_boot?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

logging:
  level:
    com.baomidou.mybatisplus.samples: debug

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: top.xym.springboot.task.entity

gaode:
  api:
    key: bcc5750c3978e70b483018215cb7e188